/**
 * */

#include <stdint.h>

typedef struct IoRegType {
    uint8_t PINA;
    uint8_t DDRA;
    uint8_t PORTA;
    uint8_t PINB;
    uint8_t DDRB;
    uint8_t PORTB;
    uint8_t PINC;
    uint8_t DDRC;
    uint8_t PORTC;
    uint8_t PIND;
    uint8_t DDRD;
    uint8_t PORTD;
    uint8_t PINE;
    uint8_t DDRE;
    uint8_t PORTE;
    uint8_t PINF;
    uint8_t DDRF;
    uint8_t PORTF;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t TIFR0;
    uint8_t TIFR1;
    uint8_t TIFR2;
    uint8_t TIFR3;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t PCIFR;
    uint8_t EIFR;
    uint8_t EIMSK;
    uint8_t GPIOR0;
    uint8_t EECR;
    uint8_t EEDR;
    uint8_t EEARL;
    uint8_t EEARH;
    uint8_t GTCCR;
    uint8_t TCCR0A;
    uint8_t TCCR0B;
    uint8_t TCNT0;
    uint8_t OCR0A;
    uint8_t OCR0B;
    uint8_t PLLCSR;
    uint8_t GPIOR1;
    uint8_t GPIOR2;
    uint8_t SPCR;
    uint8_t SPSR;
    uint8_t SPDR;
    uint8_t : 8;
    uint8_t ACSR;
    uint8_t OCDR;
    uint8_t : 8;
    uint8_t SMCR;
    uint8_t MCUSR;
    uint8_t MCUCR;
    uint8_t : 8;
    uint8_t SPMCSR;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t RAMPZ;
    uint8_t : 8;
    uint8_t SPL;
    uint8_t SPH;
    uint8_t SREG;
    uint8_t WDTCSR;
    uint8_t CLKPR;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t PRR0;
    uint8_t PRR1;
    uint8_t OSCCAL;
    uint8_t : 8;
    uint8_t PCICR;
    uint8_t EICRA;
    uint8_t EICRB;
    uint8_t PCMSK0;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t TIMSK0;
    uint8_t TIMSK1;
    uint8_t TIMSK2;
    uint8_t TIMSK3;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t XMCRA;
    uint8_t XMCRB;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t ADCL;
    uint8_t ADCH;
    uint8_t ADCSRA;
    uint8_t ADCSRB;
    uint8_t ADMUX;
    uint8_t : 8;
    uint8_t DIDR0;
    uint8_t DIDR1;
    uint8_t TCCR1A;
    uint8_t TCCR1B;
    uint8_t TCCR1C;
    uint8_t : 8;
    uint8_t TCNT1L;
    uint8_t TCNT1H;
    uint8_t ICR1L;
    uint8_t ICR1H;
    uint8_t OCR1AL;
    uint8_t OCR1AH;
    uint8_t OCR1BL;
    uint8_t OCR1BH;
    uint8_t OCR1CL;
    uint8_t OCR1CH;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t TCCR3A;
    uint8_t TCCR3B;
    uint8_t TCCR3C;
    uint8_t : 8;
    uint8_t TCNT3L;
    uint8_t TCNT3H;
    uint8_t ICR3L;
    uint8_t ICR3H;
    uint8_t OCR3AL;
    uint8_t OCR3AH;
    uint8_t OCR3BL;
    uint8_t OCR3BH;
    uint8_t OCR3CL;
    uint8_t OCR3CH;
    uint8_t UHCON;
    uint8_t UHINT;
    uint8_t UHIEN;
    uint8_t UHADDR;
    uint8_t UHFNUML;
    uint8_t UHFNUMH;
    uint8_t UHFLEN;
    uint8_t UPINRQX;
    uint8_t UPINTX;
    uint8_t UPNUM;
    uint8_t UPRST;
    uint8_t UPCONX;
    uint8_t UPCFG0X;
    uint8_t UPCFG1X;
    uint8_t UPSTAX;
    uint8_t UPCFG2X;
    uint8_t UPIENX;
    uint8_t UPDATX;
    uint8_t TCCR2A;
    uint8_t TCCR2B;
    uint8_t TCNT2;
    uint8_t OCR2A;
    uint8_t OCR2B;
    uint8_t : 8;
    uint8_t ASSR;
    uint8_t : 8;
    uint8_t TWBR;
    uint8_t TWSR;
    uint8_t TWAR;
    uint8_t TWDR;
    uint8_t TWCR;
    uint8_t TWAMR;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t UCSR1A;
    uint8_t UCSR1B;
    uint8_t UCSR1C;
    uint8_t : 8;
    uint8_t UBRR1L;
    uint8_t UBRR1H;
    uint8_t UDR1;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t UHWCON;
    uint8_t USBCON;
    uint8_t USBSTA;
    uint8_t USBINT;
    uint8_t : 8;
    uint8_t : 8;
    uint8_t OTGCON;
    uint8_t OTGIEN;
    uint8_t OTGINT;
    uint8_t UDCON;
    uint8_t UDINT;
    uint8_t UDIEN;
    uint8_t UDADDR;
    uint8_t UDFNUML;
    uint8_t UDFNUMH;
    uint8_t UDMFN;
    uint8_t : 8;
    uint8_t UEINTX;
    uint8_t UENUM;
    uint8_t UERST;
    uint8_t UECONX;
    uint8_t UECFG0X;
    uint8_t UECFG1X;
    uint8_t UESTA0X;
    uint8_t UESTA1X;
    uint8_t UEIENX;
    uint8_t UEDATX;
    uint8_t UEBCLX;
    uint8_t UEBCHX;
    uint8_t UEINT;
    uint8_t UPERRX;
    uint8_t UPBCLX;
    uint8_t UPBCHX;
    uint8_t UPINT;
    uint8_t OTGTCON;
} IoRegType;

extern IoRegType ioregs;
